# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_NPY=110  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=110  CONDA_PY=34
    - CONDA_NPY=111  CONDA_PY=34
    - CONDA_NPY=110  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XuIIvhZaggjPVd3VIUC4FBmpfJK14p+D7ysPOiD+BizPRN0jmPIJJD6MhBjqKKshgHSt8tvwhg4BKot4UDa4FOfetXIvTOmouppmkE2KjO94evM3xumsZi9PRQwNDLo+H3h4nNsFMkLJwzgiJ2a3Nh39Yqmn5mbj4vEfbbaCNkueilS0SkIHj53x/lrIjq+Dt0JWwrfMACk4CvF4VJXUr6iu7k3GElTln1QmEPTUlVd6t8JCut8aSucCeU15AwwN/Jp16XmWP8lZnTkesc2BZoFUJp4sQbzA3t6Xy9Slg1VJNln1IIgTy60CPTu6C4aPgJT0b50K94m+v+w7JsApKnxFBIG/5cBkB35RvQvWMFWPGXmh0YEmKw5iUlLOZYJLpcf5weFDbp/SXWOapiyQdMeqxfRgarQiEumawfp7evwMoVyxjOHY1UYwRLB52bjilyVRbhrJ/4I5MQM2xbKkzjg8WSvzn8PlF6AbHfgYPWkj2VYuXOBCBJhsQIVvQbagPb+7YejuYLkk+ZAaWGrbxOwaBQmhcc4wcQfFWV7tHu/aGt3ZpOFG88ZjiE42v778itFKgsRuwcZSoXqGtsKfdlcjWTJkqOhTMN0Fxud/9G7+FleYCVFYHLzK8WuTPp3RIYeaTtoDrvzdWgApa8mZtfvDDclm/HdMVkHKc+Vd4mk="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
