# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "aL4dTWOLkBk3o2zV1KdVUnP7tbhC8fK/9V8oDOi1p33uqd/kE2e9Y6VjVBiuQD8fFsKXQIZYc7cHU/oLxABoGTp2Qir+N8YFNYfkf1lEEH4y68yhj9U+B1XJEXQ0ImgKvX/Yp+/sBejPZZp+/FBGU6rVpaNZ3fD8M7yhEvfAlu1i94psmXIInK+Sp0T//VPiQmUnI4oDn6RpE4Y0z0ja+COpDa4EMkRCA6nRCeoYz5LAyDbmi6uClmhdp9D25OqDg38WVz8SqeqGMjywYYVSfjOd/+APOFh/eu8893nVD2H2+IcLlxO9YtvNQDfGoXeZeI20la/5vdbBAQN87hvMQizFdvmWCMmV7romU2xOYXO1E63oNkcDpwRvuVgZHqvjETLRhmAszxxgFf7ZD+fZjvDlEfr03ymJqTAQY/qDhH2QM6yo+Vn/nG5VxNR947CP6KbJQWui87bnw6yyyMDgDuexVjoAu3NCfbqhjAB2TCbIRBy+Q+IMy5I1u8LntOz4RDAXXngKOLZ4BjDDry/LvrBA/oGLzqu0xe6kilEDAy7Ys/46sd1+QyHc9hWNcMq9MlayJckK/+o2Y6/Q74JniQ4PE6IF1wvupu/eVo7i9nBbhUpyNl2+bLUWKTOJ382EmLtCQ/1LovIDVGzAc3SxD1C4CkGDWpFYM6vnF/do1/M="

matrix:
  include:
    - env: CONFIG=osx_python2.7 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

    - env: CONFIG=osx_python3.6 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

    - env: CONFIG=osx_python3.7 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"

  - if [[ ${PLATFORM} =~ .*osx.* ]]; then ./.travis/run_osx_build.sh; fi
