travis:
  secure:
    BINSTAR_TOKEN: LCr7LRbC7+6R4N1wcEBs+aKPI+DzRIm6D+0LjJGlDR/W3/MSg+9PM6woTi2Wgcuc71ey3a4fnaKLXOGSD9T4n6BIMbnRHTW6rsP60KthJVBxmSZcvXR4/oS9EJI0NTi6aUEtf4iWtYT3wk8B6Y4wBEXfjsCvU8CjsczZLpNecL9mSJed1Hw/7vgnIQpCnGwpa0V7NFkQaDEEsPD4LzMML8Juo56UNY3lsow3+F4r+0CMOvlVbW+4+VFdLnYs8v4TCzqC8deRZx97NPtpcSUSYdGtgBULr32IVDYBmSs1z5tBRxpRbvJ6oCKWIEB0/Mj3l4DfS1M57Y+44gZxW9qx2frxGLQlx+2Brp/SdcnjtpAwypJ1XmZ9b5zVE0iBh7JLoL2QX5vZ8Ql5NZDhp/mG4TQDJxqDJrA/hdjN3z95EIdEYWzMXLyKT5a3AYmyjexHt8WGPTqQtaciZNL0+sifC04ScwcpXbPhhMH1tMat/E3b+zLttOdpBjCZ4mCTXYwEb+iV4QxCjfE27zxxe0eMHmAZtbFP9EDsjXloECAjmFtpdDsP+xpLyRorn6SfOaWFc9f72Xfkn9zCO5m7okYlHDvr6KPxAcOqzcvjBi28S+dhdNsEc2XZ9gCKchymm2YNTY8pzkkp+PN149/UOhyfE1CfgYRlC5rU1A+Oexezwu0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
